### ISSUE TITLE
Publish glea on npm

### ISSUE THREAD

**Issue by TimPietrusky** [terabaud/glea#4]
**Is your feature request related to a problem? Please describe.**
I want to install glea into my project, so it would be nice if it's published on npm, so I don't have to copy / paste the files manually. 

**Describe the solution you'd like**
Publish glea on npm.

**Describe alternatives you've considered**
Download the code and add it manually to my project.

**Comment by terabaud** [comment]
In progress :) I think I will seperate all the optional things into separate modules (eg the matrix and vector classes), what do you think?

**Comment by terabaud** [comment]
I think I will move the linear algebra stuff into [Ella](https://github.com/terabaud/ella).

**Comment by TimPietrusky** [comment]
I think it makes sense to have separate modules so you can keep the footprint low if you only want to use the core.

**Comment by terabaud** [comment]
Agreed, the documentation needs some work :)

**Comment by terabaud** [comment]
It's live :) https://www.npmjs.com/package/glea
